project_id = "rfydswsdjwfgmzdqwhhb"

[functions.send-audit-notification]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.send-hero-lead]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
